//REMOVE ALL GAMES AND BOX SCORES, IF GAME NEVER HAS END
// 1) CREATE SCRIPT THAT GOES THROUGH ALL JSON FILES
//   - IF GAME DOESN'T HAVE END_GAME STAT
//      - DELETE ALL PLAYER AND TEAM BOX SCORES RELATED TO GAME
//      - THEN, DELETE GAME
// 2) DELETE ALL BOX SCORES AND RERUN BOX SCORE SCRIPT
// 3) DELETE ALL AVERAGES AND RERUN AVERAGES SCRIPT
