export const averageStatHeaders = {
  FG: "fg",
  FGA: "fga",
  "FG%": "fg_pct",
  "3PTM": "three_make",
  "3PTA": "three_attempt",
  "3PT%": "three_pct",
  FTM: "ftm",
  FTA: "fta",
  "FT%": "ft_pct",
  ORB: "orb",
  DRB: "drb",
  TRB: "trb",
  AST: "ast",
  STL: "stl",
  BLK: "blk",
  TO: "to",
  PF: "pf",
  PTS: "pts",
};
